CREATE DATABASE IF NOT EXISTS BooksMania;

USE BooksMania;

CREATE TABLE Users (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
address VARCHAR(250) NOT NULL,
status ENUM ("online", "offline") NOT NULL);

CREATE TABLE Books (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
author VARCHAR(250) NOT NULL,
title VARCHAR(250) NOT NULL,
guid INT NOT NULL UNIQUE
);

CREATE TABLE Users_Books (
book_id INT NOT NULL,
user_id INT NOT NULL,
PRIMARY KEY(book_id, user_id),
FOREIGN KEY (book_id) REFERENCES Books(guid) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);